if(!('Q' in window)) window.Q={geografia:{},matematica:{},fisica:{},quimica:{},ingles:{},sociologia:{},historia:{},biologia:{}};
Q.geografia.facil = [
 	{ pergunta:'A cristalografia consegue identificar materiais que reduzem o custo energético de painéis solares e moinhos de vento. Os nomes dos modos de geração de energia por meio desses instrumentos são:', dificuldade:"facil", a:'Solar e heliotérmica', b:'Eólica e solar', c:'Biomassa e heliotérmica', resposta:'b' },
	{ pergunta:'A cristalografia mudou o modo com o qual vemos o mundo pelo lado geográfico e geológico. As opções abaixo mostram áreas em que a cristalografia atua e que foram melhoradas com a ação dela. A opção que mais se refere a inovações em pesquisas geológicas e geográficas é a de letra:', dificuldade:"facil", a:'Novos materiais, como ecrãs televisivos e cartões de memória informáticos', b:'A concepção de medicamentos', c:'A mineralogia', resposta:'c'},
	{ pergunta:'Com o uso correto das pesquisas cristalográficas, é certo afirmar que se pode:', dificuldade:"facil", a:'esperar da humanidade um uso mais eficiente e econà´mico da água não-potável para lavar carros e casas', b:'diminuir os impostos sobre a energia elétrica uma vez que os estudos cristalográficos podem ampliar os recursos de transformação da energia', c:'reduzir o número de alimentos disponíveis para parte da população mundial', resposta:'b'},
	{ pergunta:'A Mina Mir é a maior mina de extração de diamantes do mundo. Ela fica localizada na Sibéria e tem 525 metros de profundidade e 1200m de diâmetro. O país onde ela fica é:', dificuldade:'facil', a:'Holanda', b:'Rússia', c:'Estados Unidos', resposta:'b'}
];
Q.geografia.medio = [
	{ pergunta:'A cristalografia pode ser aplicada para analisar solos e criar proteínas vegetais para desenvolver culturas mais resistentes a ambientes deteriorados. Das alternativas abaixo, a única que indica corretamente uma causa para a deterioração dos solos é a:', dificuldade:"medio", a:'alta concentração de gás carbà´nico na atmosfera', b:'salinização do solo', c:'ausência de plantio em terreno aberto', d:'regularidade de chuvas', resposta:'b'},
	{ pergunta:'Dos país-membros da União Internacional de Cristalografia, estão os dois principais países que se destacaram economicamente, cientificamente e belicamente com o fim da Segunda Guerra Mundial. São eles:', dificuldade:'medio', a:'Estados Unidos e Japão', b:'Estados Unidos e China', c:'Estados Unidos e Rússia', d:'China e Japão', resposta:'c'},
	{ pergunta:'Estudar cristais pode ser um desafio e tanto. Por outro lado, pode nos dar excelentes resultados. Das alternativas abaixo, a única que não apresenta uma consequência dos estudos cristalográficos é:', dificuldade:'medio', a:'aumento do nível de filtração da água não-potável a partir das nano-esponjas', b:'aumento no aproveitamento dos campos de energia eólica', c:'diminuição dos custos do ouro e da prata, essenciais para a indústria tecnológica moderna', d:'preservação maior do solo', resposta:'c'},
	{ pergunta:'De acordo com a Agência de Energia Internacional, e apesar da crise financeira global, as emissões de dióxido carbono (CO2) aumentaram, entre 2008 e 2010, 5% para 30.6 gigatoneladas (Gt). Nessa área a cristalografia recebe um papel importante porque:', dificuldade:'medio', a:'consegue desenvolver novos produtos, como materiais isolantes, que reduzem simultaneamente o consumo de energia doméstica e as emissões de carbono.', b:'consegue identificar materiais que reduzem o custo energético de usinas queimadoras do petróleo, moinhos de vento ou baterias, ao mesmo tempo que os torna mais eficientes', c:'pode identificar novos materiais capazes de aumentar o fluxo energético entre cidades, tais como os nano-tablets.', d:'Nenhuma das afirmativas acima condizem com a realidade sobre cristalografia', resposta:'a'}
];
Q.geografia.dificil = [
	{ pergunta:'Das alternativas abaixo, a única que expressa corretamente as áreas da geografia que a Cristalografia pode influenciar positivamente é:', dificuldade:'dificil', a:'Rural/alimentar, energia e saneamento de água', b:'Física, energia e rural/alimentar', c:'Medicina/criação de medicamentos, física e energia', d:'Energia, rural/alimentar e medicina/criação de medicamentos', e:'Rural/alimentar, química e medicina/criação de medicamentos', resposta:'a'},
	{ pergunta:'Nano-esponjas (filtros de torneira) e nano-tablets (purificadores de água) são possíveis derivados dos estudos cristalográficos. A identificação desses materiais pode, em determinada região:', dificuldade:'dificil', a:'aumentar o nível de consumo de água', b:'diminuir o nível de consumo de água', c:'diminuir os riscos de doenças provenientes do consumo de água não-tratada', d:'conscientizar a população sobre a importância da economia de água', e:'facilitar a chegada de água não-potável', resposta:'c'},
	{ pergunta:'No Brasil, a extração de diamantes se concentra em que estado?', a:'Minas Gerais', b:'São Paulo', c:'Rio de Janeiro', d:'Espirito Santo', e:'Paraná', resposta:'a'}
];
Q.sociologia.facil = [
	{ pergunta:'A cristalografia é usada para melhorar remédios e tratamentos. Uma das melhorias foi a criação do(a) (insira um exemplo tipo raio x), que é acessível à :', dificuldade:'facil', a:'Classe baixa e média', b:'Classe média e alta', c:'Todas as classes', resposta:'c'},
	{ pergunta:'Há dois mil anos, duas civilizações descobriram o processo de cristalização do açúcar e do sal. Que civilizações foram essas?', dificuldade:'facil', a:'Romanas e Chinesas', b:'Gregas e Chinesas', c:'Hindus e Chinesas', resposta:'c'}
];
Q.sociologia.medio = [
	{ pergunta:'A adesão da cristalografia como fonte de pesquisa em um país pode levar a avanços, benéficos à  sociedade, em setores como:', dificuldade:'medio', a:'Nenhum', b:'Saúde, Educação e Industrial', c:'Comércio', d:'D Apenas da saúde', resposta:'b'},
	{ pergunta:'Descobertas da cristalografia podem alterar os fatos sociais, por serem inovadores. Nesse contexto, quais seriam mais facilmente afetados?', dificuldade:'medio', a:'Dogmas religiosos', b:'Costumes', c:'Regras jurídicas', d:'Sistemas financeiros', resposta:'b'}
];
Q.sociologia.dificil = [
	{ pergunta:'A tecnologia vem desempenhando um papel extraordinário e cada vez mais vital na sociedade. Qual das alternativas abaixo apresenta um material de alta tecnologia desenvolvido com base na cristalografia?', dificuldade:'dificil', a:'Bateria', b:'Lâmpada', c:'Interruptor', d:'Internet sem fio', e:'Cartão de memória', resposta:'e'}
];
Q.biologia.facil = [
	{ pergunta:'Leia as afirmativas ao lado:<br />I- a cristalografia é o estudo dos "cristais", <br />II- patógenos como o vírus são seres autamente mutáveis, <br />III- a cristalografia não possui reconhecimento em estudos biológicos, já que não apresenta resultados nem pesquisas paupáveis para novos investidores. <br /><br />Qual das altenativas abaixo esta certa:', dificuldade:'facil', a:'apenas a I', b:'II e III', c:'I e II', resposta:'c'},
	{ pergunta:'Uma das técnicas usadas para o ensaio de cristalização é:', dificuldade:'facil', a:'Método de quebra da molécula', b:'Método da difusão de vapor', c:'Método de transfusão', resposta:'b'}, 
	{ pergunta:'Como é possível chegar a um modelo atômico do cristal?', dificuldade:'facil', a:'por um mapa de densidade eletrônica', b:'por experiências em laboratório', c:'nenhuma das anteriores', resposta:'a'},
	{ pergunta:'De quantas formas o cristal pode ser utilizado quando está no sentido de perfeição de desenvolvimento?', dificuldade:'facil', a:'1', b:'2', c:'3', resposta:'c'}
];
Q.biologia.medio = [
	{ pergunta:'No sangue de pessoas que foram infectadas por um dado vírus mas que o conseguiram vencer, é possível identificar os raros anticorpos realmente protectores. E a seguir, graças à  técnica de ______________ __ ____ _, numa espécie de engenharia molecular ao contrário, sabe-se derivar da estrutura dos anticorpos a estrutura dos fragmentos virais que deram origem à  produção desses anticorpos. Dado o texto acima, responda: Qual o método útilizado pela pesquisa citada acima?', dificuldade:'medio', a:'in vitro', b:'cristalografia de raios X', c:'teste de insolina', d:'cristalografia por endagação', resposta:'b'},
	{ pergunta:'A difração de raios-x aplicada à analise de cristais de macromoléculas biológicas é a técnica que mais tem influenciado a bioquímica estrutural e contribui principalmente para:', dificuldade:'medio', a:'O conhecimento da estrutura tridimensional de proteínas, ácidos nucléicos e vírus', b:'A descoberta para a cura do câncer', c:'Reposição de ossos quebrados', d:'Nenhuma das anteriores', resposta:'a'},
	{ pergunta:'Qual é a estratégia usada para induzir a cristalização de macromoléculas?', dificuldade:'medio', a:'Ferver a 100 °C', b:'Atingir lentamente um estado solúvel', c:'Esfriar a -3°C', d:'Até Atingir 50 Fahrenheit', resposta:'b'},
	{ pergunta:'Como as moléculas se encontram na estrutura interna dos cristais?', dificuldade:'medio', a:'Empacotadas e unidas', b:'Espalhadas por todo o cristal', c:'Fora da cristal', d:'Empacotadas e desunidas', resposta:'a'},
	{ pergunta:'Como se chama a estrutura cristalina que da origem aos sólidos cristalinos?', dificuldade:'medio', alterantiva_a:'Célula Unitária', b:'Vectores', c:'Simetria Translacional', d:'Magnetização', resposta:'a'}
];
Q.biologia.dificil = [
	{ pergunta:'Quais são as principais forças que mantém a integridade dos cristais?', dificuldade:'dificil', a:'Dipolo-Dipolo', b:'Dipolo Induzido', c:'Ponte de Hidrogenio', d:'Dipolo Permanente', e:'Forças de London', resposta:'c'},
	{ pergunta:'O cristal tem sua estrutura interna formada por:', dificuldade:'dificil', a:'Dimensionalmente ordenada e não periódica', b:'Moléculas separadas e empacotadas por meio de uma interação covalente', c:'Dimensionalmente não ordenada e não periódica', d:'Moléculas desempacotadas e separadas por meio de uma interação covalente', e:'Tridimensionalmente ordenada e periódica,onde moléculas estão empacotadas e juntas por meio de uma interação covalente.', resposta:'e'},
	{ pergunta:'O que é um grupo pontual da malha cristalina?', dificuldade:'dificil', a:'Proteínas', b:'Fibra de carbono', c:'Redes de Bravais', d:'Minerais', e:'Sistema de cristalização', resposta:'e'}
];
Q.ingles.facil = [
	{ pergunta:'In the last 100 years, how many scientists have won the Nobel Prize for their studies on crystallography?', dificuldade:'facil', alterantiva_a:'100', b:'45', c:'54', resposta:'b'},
	{ pergunta:'Which Latin American government has a project to create a mega company of medications using chemical and biological concepts of crystallography to improve the life of low-income class members?', dificuldade:'facil', a:'Chile', b:'Brazil', c:'Argentina', resposta:'b'},
	{ pergunta:'In which way did the use of crystals contribute most to the Second Industrial Revolution?', dificuldade:'facil', a:'In the production of automobiles', b:'In the production of films', c:'Making new drugs', resposta:'a'},
	{ pergunta:'Mineralogy is a subject of geology within crystallography, specialized in the scientific study of chemistry, crystal structure, and physical and optical properties of minerals. Which of these studies is not within mineralogy?', dificuldade:'facil', a:'Processes of mineral origin and formation', b:'Minerals geographical distribution', c:'Use of minerals in pharmaceutical processes', resposta:'c', 
	d:'The water would need to be combined with other substances', resposta:'c'}
];
Q.ingles.medio = [
	{ pergunta:'2014 is the International Year of Crystallography because it celebrates:', dificuldade:'medio', a:'100 years since the first Nobel Prize about crystallography was won.', b:'100 years since the discovery of X-ray crystallography.', c:'100 years since the first geometry study on crystals.', d:'100 years since the death of Dorothy Hodgkin.', resposta:'b'},
	{ pergunta:"The crystallographic work on DNA fibers was initiated by Maurice Wilkins and perfected by Rosalind Franklin. It was Franklin's unpublished diffraction patterns, seen without her knowledge, which provided key features to Watson and Crick, who built a model that was consistent with the existing data. The three groups then published back-to-back papers describing DNA as a double helix with the phosphates on the outside of the helix, containing strands running in reverse directions and pairing purine and pyrimidine bases across the helix.It is known that after the development of the research mentioned in the text, the 1962 Nobel Prize in Physiology or Medicine was awarded to Watson, Crick and Wilkins. Regarding the text above, it is plausible to infer that:", dificuldade:'medio', a:'They won the Prize because they corrected the chemical structures of the nucleotide bases.', b:'Rosalind Franklin wasnâ€™t awarded the Prize, although she was still alive in 1962.', c:'Their discovery led to an extensive knowledge of the genetic basis of heredity and disease, which is a reason for winning the Prize.', d:"Rosalind Franklin's publications were essential in the discovery and description of the double helix.", resposta:'c' },
	{ pergunta:'Two thousand years ago, two civilizations discovered the process of crystallization of sugar and salt, which later lead to the deeper studies in crystallography that we have nowadays. Which were these civilizations?', dificuldade:'medio', a:'Chinese and Egyptians', b:'Russian and Chinese', c:'Sumerian and Syrian', d:'Chinese and Hindus', resposta:'d'},
	{ pergunta:'Crystallography can benefit the industry in various ways. One of them is in the production of:', dificuldade:'medio', a:'clothing', b:'medication', c:'food', d:'perfumes', resposta:'b'},
	{ pergunta:'In mineralogy and crystallography, a crystal structure is a unique arrangement of atoms or molecules in a crystalline liquid or solid. Identify which of these examples has the strongest structure:', dificuldade:'medio', a:'Aluminum', b:'Brass', c:'Copper', d:'Diamond', resposta:'d'}
];
Q.ingles.dificil = [
	{ pergunta:'The early 1980s marked the expansion of crystallographic analysis from organic materials and isolated proteins to more complex biological samples. The first crystal structures of plant RNA viruses revealed the inherent symmetry of ___________ assemblies, and the subsequent elucidation of a surface antigen of influenza virus provided the first structure of pathological relevance. The most appropriate term to fill the blank is:', dificuldade:'dificil', a:'protein components', b:'human viral pathogen', c:'cell nucleus', d:'viral capsid', e:'antigenic properties', resposta:'d'},
	{ pergunta:'Snow is formed under a variety of conditions; there is no crystal with the same form (so as with people). Supposing snowflakes could have the same crystal structure, though, in what condition would that happen?', dificuldade:'dificil', a:'They would have to be put into specific molds', b:'The water would have to be sterilized', c:'The various types of water on Earth would also need to present the same structure', d:'The water would need to be combined with other substances', e:'None of the above', resposta:'c'}, 
	{ pergunta:'By running a MRA (magnetic resonance analyzer) on tap water from Shinagawa, Tokyo, it was possible to observe that it’s crystalline formation presented itself in a grotesque and dark way. However, in a second stage of analysis, the crystal was shown perfectly structured and transparent. That happened due to:', dificuldade:'dificil', a:'chemicals released into the water', b:'an immunity code sent by positive energetic waves', c:'exposure of the sample to different environments', d:'water boiling', e:'water decantation', resposta:'b'}
];
Q.fisica.facil = [
	{ pergunta:'Qual o método mais utilizado no estudo da estrutura cristalina?', dificuldade:'facil', a:'Microscopia óptica', b:'Difração de ondas', c:'Observação à lupa', resposta:'b'},
	{ pergunta:'A cristalografia de macromoléculas é a ciência destinada a estudar sistemas biológicos através da determinação da estrutura:', dificuldade:'facil', a:'Bidimensional', b:'Tridimensional', c:'Plana', resposta:'b'},
	{ pergunta:'Informações sobre a estrutura de uma molécula podem ser obtidas por várias metodologias. O método cristalográfico apresenta-se como o mais adequado devido à:', dificuldade:'facil', a:'Alta resolução com que se pode descrever a densidade eletrônica', b:'Precisão de suas imagens', c:'Resolução avançada das novas técnicas radiocristalógrafas', resposta:'a'}
];
Q.fisica.medio = [
	{ pergunta:'Na Cristalografia o padrão de difração é usado para determinar:', dificuldade:'medio', a:'O arranjo e os espaçamentos entre os átomos', b:'O arranjo e os espaçamentos entre as moléculas', c:'O arranjo e os espaçamentos entre as células', d:'O arranjo e os espaçamentos entre os vírus', resposta:'a'},
	{ pergunta:'A cristalografia física está relacionada:', dificuldade:'medio', a:'Ao estudo da forma dos cristais', b:'Ao estudo das relações entre a forma e composição química dos cristais', c:'Ao estudo das relações entre a forma e propriedades ópticas dos cristais', d:'Ao estudo da disposição dos átomos no interior dos cristais', resposta:'c'},
	{ pergunta:'Como os raios x podem ajudar na observação da estrutura dos materiais cristalinos?', dificuldade:'medio', a:'Por serem raios altamente luminosos, iluminam intensamente a estrutura do material, tornando-o visível a "olho nu"', b:'Com eles podem-se identificar as próprias posições dos átomos ou mesmo acompanhar em tempo real seus rapidíssimos movimentos quando a estrutura cristalina de um material é alterada por uma transição de fase.', c:'Devido a sua radiação, quebram o material estudado em milhares de pedaços, até obter a molécula desejada para o estudo.', d:'Podem ser utilizados na extração dos cristais, extraindo-os das minas.', resposta:'b'},
	{ pergunta:'A cristalografia de raios x é uma técnica que consiste em fazer passar um feixe de raio x. O feixe se difunde em várias direções devido:', dificuldade:'medio', a:'Ao formato dos cristais', b:'Ao encontro de dois feixes', c:'Simetria do agrupamento de moléculas', d:'Simetria do agrupamento de átomos', resposta:'d'}
];
Q.fisica.dificil = [
	{ pergunta:'A física médica utiliza um meio de investigação na produção de imagens especial, que é mais preciso que o meio original. Qual das opções abaixo é este meio?', dificuldade:'dificil', a:'Radiografia por contraste de fase', b:'Lupa', c:'Difração de ondas', d:'Raio – X', e:'Microscopia óptica', resposta:'a'},
	{ pergunta:'Por que a difração de raios-X é muito eficiente quando o material investigado é cristalino?', dificuldade:'dificil', a:'Porque o brilho dos cristais atrai os raios-X.', b:'Porque o brilho dos cristais afasta os raios-X.', c:'Porque seus átomos e moléculas estão dispostos regularmente.', d:'Porque seus átomos e moléculas estão dispostos irregularmente.', e:'Porque os meios opacos quebram os raios-X.'},
	{ pergunta:'Como a cristalografia pode ajudar na redução do consumo de energia?', dificuldade:'dificil', a:'Utilizando o brilho dos cristais para iluminar ambientes fechados.', b:'Fracionando os cristais de água, nas hidrelétricas, aumentando sua capacidade energética.', c:'Multiplicando os raios luminosos conduzidos pelos geradores.', d:'Gerando energia cristalatômica.', e:'Ajudando a desenvolver novos produtos, como materiais isolantes.', resposta:'e'}
];
Q.historia.facil = [	
	{ pergunta:'No final do século XIX o raio X foi descoberto. O que acontecia no mundo enquanto isso?', dificuldade:'facil', a:'Imperialismo europeu', b:'Primeira guerra mundial', c:'Imperialismo napoleônico', resposta:'a'},
	{ pergunta:'Em 2011 um israelense ganhou o prêmio Nobel de química por descobrir os quase- cristais. Estes, possuem uma estrutura atômica, que ao contrário dos cristais comuns, possuem uma ordem aperiódica, eles também se diferenciam dos outros cristais por possuir diferentes propriedades elétricas e físicas. Estudos tentam aplicar o material em motores a diesel e eletrodomésticos. O nome do ganhador do prêmio foi:', dificuldade:'facil', a:'James Watson', b:'Adam Riess', c:'Daniel Shechtman', resposta:'c'}
];
Q.historia.medio = [
	{ pergunta:'Quando começou realmente a história da cristalografia?', dificuldade:'medio', a:'1678', b:'1669', c:'1696', d:'1786', resposta:'b'},	
	{ pergunta:'"A cristalografia moderna tem por objetivo o conhecimento da estrutura dos materiais a nível atômico." Essa definição foi estabelecida em 1911 quando, paralelamente, houve um acontecimento muito importante para a história da China. Que acontecimento foi esse?', dificuldade:'medio', a:'Revolução Comunista', b:'Guerra Civil Chinesa', c:'Guerra do Ópio', d:'Revolução Chinesa', resposta:'d'},
	{ pergunta:'Na canção “Diamante Verdadeiro”, famosa na MPB, qual dos cantores a seguir não gravou uma versão?', dificuldade:'medio', a:'Caetano Veloso', b:'Cássia Eller', c:'Tom Jobim', d:'Maria Bethânia', resposta:'c'}
];
Q.historia.dificil = [
	{ pergunta:'Em 1895 o estudo sobre a simetria dos cristais evoluía, foi quando o raio x foi descoberto por Willhelm Conrad Röntgen que era?', dificuldade:'dificil', a:'Russo', b:'Norueguês', c:'Alemão', d:'Inglês', e:'Holandês', resposta:'c'},
	{ pergunta:'Em qual contexto histórico surgiu o uso do LCD?', dificuldade:'dificil', a:'Revolução russa', b:'Revolução técnico-científica', c:'Renascimento', d:'Segunda guerra mundial', e:'Primeira guerra mundial', resposta:'b'},
	{ pergunta:'Quem canta: "O amor quando se parte assim é um cristal quebrado, não cola nunca mais, o sol não se refaz"?', dificuldade:'dificil', a:'Maria Gadu', b:'Ana Carolina', c:'Seu Jorge', d:'Leonardo', e:'Turma Do Pagode', resposta:'d'}
];
Q.matematica.facil = [	
	{ pergunta:'Qual o volume de um rubi em forma de cubo, com uma área de 120cm²?', dificuldade:'facil', a:'120 cm cúbicos', b:'240 cm cúbicos', c:'125 cm cúbicos', resposta:'c'},
	{ pergunta:'Aumentando-se a aresta de um cubo em 10%, a sua área total ficara aumentada em?', dificuldade:'facil', a:'10%', b:'100%', c:'21%', resposta:'c'}
];
Q.matematica.medio = [	
	{ pergunta:'A área lateral de um prisma regular hexagonal e o triplo da área da base desse prisma. Calcule o seu volume, sabendo que a sua base tem 2p=12cm', dificuldade:'medio', a:'9cm3', b:'8cm3', c:'8cm3', d:'810cm3', resposta:'a'},
	{ pergunta:'Em um prisma triangular regular, a altura mede 2√3 cm, e a área lateral é o quádruplo da área da base. Calcular a área total desse prisma:', dificuldade:'medio', a:'54√3 cm²', b:'36√3 cm²', c:'6 cm²', d:'54√2 cm²', resposta:'a'}
];
Q.matematica.dificil = [	
	{ pergunta:'Um cristal com a forma de um prisma hexagonal regular, após ser cortado e polido, deu origem a um sólido de 12 faces triangulares congruentes. Calcule a razão entre os volumes do sólido e do prisma:', dificuldade:'dificil', a:'1/3', b:'1/4', c:'√2/2', d:'2/3', e:'1', resposta:'b'},
	{ pergunta:'A área lateral de um prisma regular hexagonal é o triplo da área desse prisma. Calcule o volume, sabendo que a base desse prisma tem o perímetro igual a 12 cm.', dificuldade:'dificil', a:'5 cm cúbicos', b:'20 cm cúbicos', c:'4 cm cúbicos', d:'9 cm cúbicos', e:'1 cm cúbico', resposta:'d'}
];
Q.quimica.facil = [
	{ pergunta:'A técnica de difração de raios x serve para determinar a estrutura dos cristais, que foi sua principal utilização no início, mas também para outros objetivos como por exemplo:', dificuldade:'facil', a:'Facilitar o transporte de cristalização', b:'Passar de um estado físico para outro', c:'Análise química de amostras', resposta:'c'},
	{ pergunta:'A cristalografia abrange que área?', dificuldade:'facil', a:'biológicos, físicos ou químicos', b:'humanos', c:'sobre a vegetação e animais', resposta:'a'},
	{ pergunta:'Sobre Cristalografia é correto afirmar que:', dificuldade:'facil', a:'É uma ciência atrasada que não trará nenhum beneficio', b:'Ela só esta ligada a área da química', c:'A Cristalografia tem como ponto de partida o fato de ser uma disciplina que sustenta todas as ciências, já que os cristais estão em toda parte', resposta:'c'}
];
Q.quimica.medio = [
	{ pergunta:'Um cristal é caracterizado de que forma?', dificuldade:'medio', a:'Sólido homogêneo', b:'Sólido heterogêneo', c:'Líquido homogêneo', d:'Líquido heterogêneo', resposta:'e'},
	{ pergunta:'Das alternativas abaixo sobre alguns funções da cristalografia a que esta incorreta é:', dificuldade:'medio', a:'Métdo para a síntese de um Anel', b:'Método para produzir foto', c:'Método para produzir aminobiphenylene', d:'Método Para produzir alimentos', resposta:'d'}
];
Q.quimica.dificil = [
	{ pergunta:'Outras Técnicas foram desenvolvidas para se estudar outras características dos matérias que não podiam por ser estudadas com os raios x, as principais são:', dificuldade:'dificil', a:'Raios Gama', b:'Ligação iônica e covalente', c:'Ligação dativa', d:'Geometria Plana', e:'Difração de elétrons e nêutrons', resposta:'e'},
	{ pergunta:'Quais os dois elementos químicos que ajudam na formação de um cristal?', dificuldade:'dificil', a:'hidrogênio e oxigênio', b:'fluor e cloro', c:'potássio e ferro', d:'alumínio e manganês', e:'carbono e argônio', resposta:'d'}
];
Q0=Q;